### ISSUE TITLE
Didn't seem to work too well with GitHub Enterprise.

### ISSUE THREAD

**Issue by annitya** [dropseed/jump#67]
Uncaught Exception:
Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
    at getRepos (/Applications/jump.app/Contents/Resources/app/src/github.js:36:13)
    at module.exports.sendError (/Applications/jump.app/Contents/Resources/app/node_modules/github/lib/index.js:867:7)
    at /Applications/jump.app/Contents/Resources/app/node_modules/github/lib/index.js:875:21
    at callCallback (/Applications/jump.app/Contents/Resources/app/node_modules/github/lib/index.js:731:9)
    at IncomingMessage.<anonymous> (/Applications/jump.app/Contents/Resources/app/node_modules/github/lib/index.js:800:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by davegaeddert** [comment]
Did you make any changes to the code to try it for enterprise? It doesn't have support for that built-in yet. We'd probably have to add some additional settings that could be used to configure it to pull repos from your enterprise instance as well as github.com. Happy to look at a pull request if you want to take a stab at it. Thanks!

**Comment by annitya** [comment]
Funny thing is, I started on the exact same project a while back, but with GHE. Let me see if I can't find that code :)

**Comment by davegaeddert** [comment]
Closed by #70, released here: https://github.com/dropseed/jump/releases/tag/v0.4.0
